%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Joeltec\Documents\MATLAB\Group2_Student_Output.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 31-Aug-2026 16:38:19

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:F6";

% Specify column names and types
opts.VariableNames = ["Name", "Tribe", "Association", "Hostel", "Friends", "Gender"];
opts.VariableTypes = ["string", "string", "string", "categorical", "string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Name", "Tribe", "Association", "Friends"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "Tribe", "Association", "Hostel", "Friends", "Gender"], "EmptyFieldRule", "auto");

% Import the data
Group2StudentOutput = readtable("C:\Users\Joeltec\Documents\MATLAB\Group2_Student_Output.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts